### ISSUE TITLE
unrecognized arguments: --dns-netcup-credentials --dns-netcup-propagation-seconds

### ISSUE THREAD

**Issue by 1337gut** [coldfix/certbot-dns-netcup#14]
After installing and running the certbot I'm getting this error:

`certbot: error: unrecognized arguments: --dns-netcup-credentials /root/.secrets/certbot/netcup.ini --dns-netcup-propagation-seconds 900`

**Comment by coldfix** [comment]
Hi,

What is your full command line?

How did you install certbot/certbot-dns-netcup?

Please make sure that certbot is installed in the same python environment as certbot-dns-netcup
