### ISSUE TITLE
Make package available on snap

### ISSUE THREAD

**Issue by JakobStaudt** [coldfix/certbot-dns-netcup#19]
It looks like the issue some people were having (and I am having it right now too), that the plugin is not recognized by certbot, is caused by using a snap installation of certbot. 
Using snap is the strongly suggested method of installation for certbot though. 
Apparently, certbot installs it's own Python and uses that, so installing the dns-netcup pip package on the normal python enviroment does not make it available to certbot. I also tried accessing the snap python and installing the plugin there but I could not get it to work. According to the certbot forum, the "correct" method of installing plugins for the snap version of certbot is installing them as snap packages ( https://community.letsencrypt.org/t/certbot-dns-plugin-listed-in-certbot-plugins-but-still-not-working/139614/9 ), so having this package on snap would probably fix this issue.

**Comment by coldfix** [comment]
Hey, thanks for the info!

I'll try to look into it. Do you have any experience with building snaps?

**Comment by JakobStaudt** [comment]
No, not at all, sadly. In the linked answer, theres another link to a guide on how to prepare the plugin for snap ( https://eff-certbot.readthedocs.io/en/stable/contributing.html#writing-your-own-plugin-snap ). Theres also a link to a script to create a snapcraft.yaml file there ( https://github.com/certbot/certbot/blob/master/tools/snap/generate_dnsplugins_snapcraft.sh ), but I am not sure if the plugin has to be modified before doing this.

**Comment by coldfix** [comment]
Hi,

I added a snap package for this that should now be usable with the certbot snap:

```
sudo snap install certbot-dns-netcup
```

You may also have to connect the plugin as follows:

```
sudo snap set certbot trust-plugin-with-root=ok
sudo snap connect certbot:plugin certbot-dns-netcup
```

Let me know if there are any problems — I haven't tested this in detail and I'm no snaxpert.
