### ISSUE TITLE
How to use this Plugin with Certbot v2.4

### ISSUE THREAD

**Issue by j54j6** [coldfix/certbot-dns-netcup#20]
Hey, 

I try to setup a certificate Server using the latest Certbot Version (2.4) - This Plugins works fine on my other Server with Certbot V.1.19 installed. 
Certbot 2.4 does not seem to find the Plugin when installed (Certbot is installed using SNAP (and for testing Python)... According to this: https://community.letsencrypt.org/t/the-requested-plugin-does-not-appear-to-be-installed/190632/2 the naming scheme was changed in V.2... - I've seen that you already changed something to allow this plugin working with Certbot 2.4 but when I use certbot plugin command it can't be find :/

Did this plugin work in general with Certbot V2.4 or is it planned to make it working? - using the SNAP installation method ^^

Thank you for this great Plugin it helped me a llot during the last years :).

~j54j6

**Comment by coldfix** [comment]
Hi, I think it's probably rather an issue of the snap installation of certbot not being connected to pip installed plugins, rather than of the certbot version, see #19. In general certbot v2 is is supported. I really should work on the snap package soon.

**Comment by j54j6** [comment]
Yes I also read this issue - and maybe but I am happy that this plugin is existing :) - I've used the apt package (python3-certbot) then it works without any issues ^^
I've tried to install this plugin in the snap venv but this wasn't working :/  - maybe only a snap package works with it ^^

In case anyone else have this problem for now using the pythion3-certbot (sudo apt install python3-certbot) is working fine with this plugin ^^
