### ISSUE TITLE
Requirement.parse('acme>=0.40.0'))

### ISSUE THREAD

**Issue by ptc** [coldfix/certbot-dns-netcup#8]
I'm getting an error when trying to run certbot-dns-netcup on Ubuntu 18.4:

pkg_resources.VersionConflict: (acme 0.31.0 (/usr/lib/python3/dist-packages), Requirement.parse('acme>=0.40.0'))

Best

**Comment by coldfix** [comment]
this plugin currently requires `acme>=0.31.0` (see `setup.cfg`), so this package is probably not responsible for this exception, unless you manually changed something.

When reporting exceptions, please give the full traceback and use code fences. It usually contains useful information as to where/why this error occurs. Also, please note the versions of installed packages (`pip list`)
